logstash:
  restart: always
  tty: true
  environment:
    CONFD_SUBDIRS: ${configs}
  ports:
  - "${udp_port_range}:${udp_port_range}/udp"
  - "${tcp_port_range}:${tcp_port_range}/tcp"
  volumes:
  - ${base_dir}/logstash/conf.d:/etc/logstash/conf.d/:ro
  - ${base_dir}/logstash/geoip:/etc/logstash/geoip/:ro
  - ${base_dir}/logstash/templates:/etc/logstash/templates/:ro
  - ${base_dir}/logstash/patterns:/etc/logstash/patterns/:ro
  command:
  - ${commandline}
  image: oorabona/logstash:2.3.3
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
