redis:
  restart: always
  tty: true
  image: redis:3.0.7
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
logstash-indexer-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  volumes:
    - "${base_dir}/logstash:/etc/logstash"
  labels:
    io.rancher.container.hostname_override: container_name
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:latest
  links:
  - redis:redis
  external_links:
  - ${elasticsearch_link}:elasticsearch
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
logstash-collector-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  volumes:
    - "${base_dir}/logstash:/etc/logstash"
  labels:
    io.rancher.container.hostname_override: container_name
logstash-collector:
  restart: always
  tty: true
  links:
  - redis:redis
  ports:
  - "${udp_port_range}:${udp_port_range}/udp"
  - "${tcp_port_range}:${tcp_port_range}/tcp"
  volumes_from:
  - logstash-collector-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: logstash:latest
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
