.catalog:
  name: "Logstash"
  version: "2.3.3-custom"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: affinity
      label: "Rancher scheduler affinity, based on hosts labels MUST NOT!"
      description: "Can be any key=value pair..."
      type: "string"
      required: true
      default: "com.domain.=value"
    - variable: "configs"
      description: |
        List of configuration (sub-) directories to load (must be under /etc/logstash/conf.d/).
      label: "Logstash configurations to load (*=all, otherwise space-separated)"
      type: "string"
      required: true
      default: "*"
    - variable: base_dir
      description: "Base directory for configuration files."
      label: "Base directory"
      type: "string"
      required: true
      default: "/srv"
    - variable: commandline
      label: "Extra commandline arguments"
      description: "Please refer to logstash documentation if needed."
      type: "string"
      required: true
      default: "-w 1"
    - variable: "udp_port_range"
      label: |
        UDP port range (low-high)
      description: "Can also be a single port"
      type: "string"
      required: true
      default: "514-5140"
    - variable: "tcp_port_range"
      label: |
        TCP port range (low-high)
      description: "Can also be a single port"
      type: "string"
      required: true
      default: "514-5140"
