.catalog:
  name: "Logstash"
  version: "2.3.3-custom"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "configs"
      description: |
        List of configuration (sub-) directories to load (must be under /etc/logstash/conf.d/).
      label: "Logstash configurations to load (*=all, otherwise space-separated)"
      type: "string"
      required: true
      default: "*"
    - variable: base_dir
      description: "Base directory for configuration files."
      label: "Base directory"
      type: "string"
      required: true
      default: "/srv"
    - variable: "udp_port_range"
      description: |
        UDP port range (low-high)
      label: "Can also be a single port"
      type: "string"
      required: true
      default: "514-5140"
    - variable: "tcp_port_range"
      description: |
        TCP port range (low-high)
      label: "Can also be a single port"
      type: "string"
      required: true
      default: "514-5140"
