masters:
  image: oorabona/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-master,datavolume-masters
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-masters

datavolume-masters:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/es/master/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/master/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4
base-master:
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2.4
  net: "container:masters"
  volumes_from:
    - datavolume-masters
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh

datanodes:
  image: oorabona/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-datanode,datavolume-datanode
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-datanode

datavolume-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/es/datanode/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/datanode/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4
base-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2.4
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh
  volumes_from:
    - datavolume-datanode
  net: "container:datanodes"

clients:
  image: oorabona/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-clients,datavolume-clients
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-clients

datavolume-clients:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/es/client/data:/usr/share/elasticsearch/data
    - ${base_dir}/es/client/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2.4

base-clients:
  labels:
    elasticsearch.client.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2.4
  volumes_from:
    - datavolume-clients
  net: "container:clients"
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh

kopf:
  image: rancher/kopf:v0.4.0
  environment:
    VIRTUAL_HOST: "${kopf_fqdn}"
    VIRTUAL_PORT: "80"
    KOPF_SERVER_NAME: 'es.dev'
    KOPF_ES_SERVERS: 'clients.elasticsearch:9200'
  labels:
    io.rancher.container.hostname_override: container_name
