.catalog:
  name: "Elasticsearch"
  version: "2.4-rancher1-custom"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: base_dir
      description: "Base directory for configuration files."
      label: "Base directory"
      type: "string"
      required: true
      default: "/srv"
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: "kopf_fqdn"
      description: "Nginx Reverse Proxy FQDN for Kopf Web Interface"
      label: "Kopf FQDN"
      type: "string"
      required: true
      default: "kopf.domain.name"
    - variable: affinity
      label: "Rancher scheduler affinity, based on hosts labels MUST NOT!"
      description: "Can be any key=value pair..."
      type: "string"
      required: true
      default: "com.domain.=value"
    - variable: datanodes_scale
      label: "Number of datanodes for this ES cluster"
      description: "Must be lower than # of Rancher nodes"
      type: "int"
      required: true
      default: 3

masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
datanodes:
  scale: ${datanodes_scale}
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "true"
        network.host: "_site_"
clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "${cluster_name}"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
       network.host: "_site_"
