nginx-proxy:
  image: oorabona/nginx-rancher-rp
  labels:
    io.rancher.container.network: true
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity: $${affinity}
  ports:
   - "80:80"
   - "443:443"
  volumes:
    - '${base_dir}/certs:/etc/nginx/certs:ro'
    - '${base_dir}/nginx/vhost.d:/etc/nginx/vhost.d'
    - '${base_dir}/nginx/html:/usr/share/nginx/html'
