version: '2'
catalog:
  name: "nginx-reverse-proxy"
  version: "latest-custom"
  description: "Automatic reverse proxy for your Web containers deployed in Rancher"
  questions:
    - variable: "NGINX_VERSION"
      label: "Version"
      description: |
        Select the NGiNX server version.
      required: true
      default: "stable"
      type: enum
      options:
        - stable
        - latest
    # - variable: base_dir
    #   description: "Base directory for configuration files."
    #   label: "Base directory"
    #   type: "string"
    #   required: true
    #   default: "/srv"
    - variable: rancher_version
      label: "Rancher Server version"
      description: "Version of Rancher Metadata API to request."
      type: "enum"
      required: true
      options:
        - 2015-07-25
        - 2015-12-19
        - 2016-07-29
        - latest
      default: "latest"
    - variable: CRON
      label: "Scheduling of updates (see later.js docs)"
      description: "Only textual representation accepted !"
      required: true
      default: "every 30 sec"
      type: "string"
    - variable: MONGODB_SERVICE
      label: "MongoDB stack/service"
      description: "MongoDB service link (MongoDB will be installed as part of this stack if empty)"
      type: "service"
      default: ""
      required: false
    - variable: "SSL_CERT"
      description: "Select SSL certificate."
      label: "SSL certificate:"
      required: true
      default: ""
      type: "certificate"
    - variable: "CONF_VOLUME_DRIVER"
      type: "string"
      label: "Volume driver for NGiNX configuration files"
      description: |
        Specifiy docker volume driver to use
      default: "local"
      required: true
    - variable: "HTML_VOLUME_DRIVER"
      type: "string"
      label: "Volume driver for NGiNX HTML files"
      description: |
        Specifiy docker volume driver to use
      default: "local"
      required: true
# services:
  # lb:
  #   scale: 1
  #   lb_config:
  #     certs: []
  #     default_cert: ${SSL_CERT}
  #     port_rules:
  #     - protocol: https
  #       service: nginx-rp
  #       source_port: 443
  #       target_port: 443
  #   health_check:
  #     response_timeout: 2000
  #     healthy_threshold: 2
  #     port: 42
  #     unhealthy_threshold: 3
  # nginx-rp:
  #   scale: 1
  #   retain_ip: true
  #   health_check:
  #     port: 80
  #     interval: 5000
  #     unhealthy_threshold: 3
  #     request_line: 'GET / HTTP/1.0'
  #     healthy_threshold: 2
  #     response_timeout: 5000
