version: '2'
catalog:
  name: "nginx-cdn"
  version: "latest-custom"
  description: "Fast and secure standalone NGiNX to server static files (CDN-like)"
  questions:
    - variable: want_global
      type: boolean
      label: "Do you want to make NGiNX Reverse Proxy a global service ?"
      description: "If so, it will be deployed in every host of this environment."
      default: false
      required: true
    - variable: host_label
      label: "Host with Label to deploy CDN on"
      description: |
        Host label to use as nginx-cdn 'value' tag.
      type: "string"
      required: true
      default: "cdn=true"
    - variable: base_dir
      description: "Base directory for CDN assets."
      label: "Assets base directory"
      type: "string"
      required: true
      default: "/home/assets"
    - variable: server_config_file
      type: "multiline"
      label: "NGiNX server config file"
      description: "Default configuration for multi domain CDN. Change at your own risk!"
      required: true
      default: ""
    - variable: cdn_config_file
      type: "multiline"
      label: "NGiNX CDN config file"
      description: "Default CDN configuration file, you can tweak it if you know what you are doing."
      required: true
      default: ""

services:
  nginx-cdn:
    metadata:
      nginx:
        cdn: |
          ${cdn_config_file}
        server: |
          ${server_config_file}
