.catalog:
  name: "sslh"
  version: "latest-custom"
  description: "SSH/HTTPS/OpenVPN multiplexer"
  questions:
    - variable: base_dir
      description: "Base directory for configuration files."
      label: "Base directory"
      type: "string"
      required: true
      default: "/srv"
    - variable: affinity
      label: "Rancher scheduler affinity, based on hosts labels!"
      description: "Can be any key=value pair..."
      type: "string"
      required: true
      default: "fq.label=value"
    - variable: ssh_host
      description: "Forward SSH connections to this hostname"
      label: "Any resolvable IP"
      type: "string"
      required: true
      default: "localhost"
    - variable: ssh_port
      description: "Forward SSH to this port"
      type: "int"
      required: true
      default: 22
    - variable: ovpn_host
      description: "Forward VPN connections to this hostname"
      label: "Any resolvable IP"
      type: "string"
      required: true
      default: "localhost"
    - variable: ovpn_port
      description: "Forward VPN to this port"
      type: "int"
      required: true
      default: 1194
    - variable: https_host
      description: "Forward HTTPS connections to this hostname"
      label: "Any resolvable IP"
      type: "string"
      required: true
      default: "localhost"
    - variable: https_port
      description: "Forward HTTPS to this port"
      type: "int"
      required: true
      default: 8443
