masters:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-master,datavolume-masters
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-masters

datavolume-masters:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/elasticsearch/master/data:/usr/share/elasticsearch/data
    - ${base_dir}/elasticsearch/master/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2
base-master:
  environment:
    TZ: "${tz}"
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2
  net: "container:masters"
  volumes_from:
    - datavolume-masters
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh

datanodes:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-datanode,datavolume-datanode
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-datanode

datavolume-datanode:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/elasticsearch/datanode/data:/usr/share/elasticsearch/data
    - ${base_dir}/elasticsearch/datanode/config:/usr/share/elasticsearch/config
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2
base-datanode:
  environment:
    TZ: "${tz}"
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh
  volumes_from:
    - datavolume-datanode
  net: "container:datanodes"

clients:
  image: agefospme/elasticsearch-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: base-clients,datavolume-clients
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes_from:
    - datavolume-clients

datavolume-clients:
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  volumes:
    - ${base_dir}/elasticsearch/client/data:/usr/share/elasticsearch/data
    - ${base_dir}/elasticsearch/client/config:/usr/share/elasticsearch/config
    - /usr/share/elasticsearch/plugins
    - /opt/rancher/bin
  entrypoint: /bin/true
  image: elasticsearch:2

base-clients:
  environment:
    TZ: "${tz}"
  labels:
    elasticsearch.client.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_ne: ${affinity}
  image: elasticsearch:2
  volumes_from:
    - datavolume-clients
  net: "container:clients"
  entrypoint:
    - sh
    - /opt/rancher/bin/run.sh

kopf:
  image: lmenezes/elasticsearch-kopf
  environment:
    TZ: "${tz}"
    VIRTUAL_HOST: "${kopf_fqdn}"
    VIRTUAL_PORT: "80"
    KOPF_SERVER_NAME: '${kopf_fqdn}'
    KOPF_ES_SERVERS: 'clients.elasticsearch:9200'
  labels:
    io.rancher.container.hostname_override: container_name
